%% Facts: Parameters will dynamically be generated by the LLM
contains_offensive_language("message", yes).
targets_individual("message", yes).
repeats_negative_phrases("message", no).
mentions_private_info("message", no).
is_anonymous("message", yes).

%% Rules for Classification

% Rule 1: Harassment
% Harassment occurs if the message contains offensive language, targets an individual, and is not anonymous.
harassment(X) :-
    contains_offensive_language(X, yes),
    targets_individual(X, yes),
    not is_anonymous(X).

harassment_response(X) :- 
    harassment(X),
    write('This is harassment.'), nl.

% Rule 2: Threat
% A threat occurs if the message contains offensive language, mentions private information, and is anonymous.
threat(X) :-
    contains_offensive_language(X, yes),
    mentions_private_info(X, yes),
    is_anonymous(X).

threat_response(X) :-
    threat(X),
    write('This is a threat.'), nl.

% Rule 3: Exclusion
% Exclusionary behavior occurs if the message repeats negative phrases, targets an individual, and does not mention private info.
exclusion(X) :-
    repeats_negative_phrases(X, yes),
    targets_individual(X, yes),
    not mentions_private_info(X).

exclusion_response(X) :-
    exclusion(X),
    write('This is exclusionary behavior.'), nl.

% Rule 4: Default for Unclassified Bullying
% Content is considered unclassified bullying if it contains offensive language but does not meet the criteria for harassment, threats, or exclusion.
unclassified_bullying(X) :-
    contains_offensive_language(X, yes),
    not harassment(X),
    not threat(X),
    not exclusion(X).

unclassified_response(X) :-
    unclassified_bullying(X),
    write('This is inappropriate content.'), nl.
