%% Facts: Parameters will dynamically be generated by the LLM
contains_offensive_language("message", yes).
targets_individual("message", yes).
repeats_negative_phrases("message", no).
mentions_private_info("message", no).
is_anonymous("message", yes).
contains_threatening_language("message", no).
contains_discriminatory_language("message", yes).
message_history("message", repeated_offenses).
message_length("message", short).

%% Rules

harassment(X) :-
    contains_offensive_language(X, yes),
    targets_individual(X, yes),
    not is_anonymous(X).

harassment_response(X) :- 
    harassment(X),
    write('This is harassment.'), nl.

threat(X) :-
    contains_offensive_language(X, yes),
    mentions_private_info(X, yes),
    is_anonymous(X).

threat_response(X) :-
    threat(X),
    write('This is a threat.'), nl.

exclusion(X) :-
    repeats_negative_phrases(X, yes),
    targets_individual(X, yes),
    not mentions_private_info(X).

exclusion_response(X) :-
    exclusion(X),
    write('This is exclusionary behavior.'), nl.

discrimination(X) :-
    contains_discriminatory_language(X, yes),
    targets_individual(X, yes).

discrimination_response(X) :-
    discrimination(X),
    write('This is discriminatory behavior.'), nl.

% Default for Unclassified Bullying
unclassified_bullying(X) :-
    contains_offensive_language(X, yes),
    not harassment(X),
    not threat(X),
    not exclusion(X),
    not discrimination(X).

unclassified_response(X) :-
    unclassified_bullying(X),
    write('This is inappropriate content.'), nl.

%% Behavioral Assessment

% Positive Message Characteristics
positive_message(X) :-
    not contains_offensive_language(X, yes),
    not contains_discriminatory_language(X, yes),
    message_length(X, long).

% Good Behavior Messages
good_behavior(X) :-
    positive_message(X),
    not targets_individual(X, yes).

% Motivated Message Characteristics
motivated_message(X) :-
    positive_message(X),
    message_history(X, no_offenses).

% Negative Behavior Assessment
negative_behavior(X) :-
    contains_offensive_language(X, yes),
    message_history(X, repeated_offenses).

% At-Risk Messages
at_risk_message(X) :-
    negative_behavior(X),
    is_anonymous(X).

% Not At Risk
not_at_risk(X) :-
    motivated_message(X),
    good_behavior(X),
    not at_risk_message(X).

% Maybe At Risk
maybe_at_risk(X) :-
    contains_offensive_language(X, yes),
    message_history(X, isolated_incident),
    not at_risk_message(X).